### ISSUE TITLE
Github action don't show the username

### ISSUE THREAD

**Issue by laurenziello** [Virtual4087/Tree2Hope#81]
in the file .github/workflows/greetings.yml
the property 
${{ github.event.pull_request.user.login }}
it seems to be ignored

![image](https://github.com/Virtual4087/Tree2Hope/assets/24606066/9d156f21-1f5b-4f3a-911b-8981d318dd99)

**Comment by SeaBebop** [comment]
![image](https://github.com/Virtual4087/Tree2Hope/assets/54507045/782f8fb6-1ed6-40ad-a1df-26a286737d2d)
Attempted a fix of the issue, the problem is that ${{ github.event.pull_request.user.login }} only works for a pull request event not an issues creation event. So I created a conditional for both cases in my forked resp.

**Comment by laurenziello** [comment]
Great!!
